global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using Microsoft.AspNetCore.Authentication.OpenIdConnect;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.IdentityModel.Logging;
global using Microsoft.IdentityModel.Tokens;
global using System.Diagnostics;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Security.Claims;
global using SameSiteMode = Microsoft.AspNetCore.Http.SameSiteMode;
global using WebApplication = Microsoft.AspNetCore.Builder.WebApplication;
