// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using App1.App1.Data.Entities;
using Microsoft.EntityFrameworkCore;

namespace App1.App1.Data;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    public DbSet<Organization> Organizations => Set<Organization>();
    public DbSet<User> Users => Set<User>();
    public DbSet<Membership> Memberships => Set<Membership>();
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<Permission> Permissions => Set<Permission>();
    public DbSet<RolePermission> RolePermissions => Set<RolePermission>();
    public DbSet<UserRole> UserRoles => Set<UserRole>();
    public DbSet<UserClaim> UserClaims => Set<UserClaim>();
    public DbSet<OrganizationClaim> OrganizationClaims => Set<OrganizationClaim>();
    public DbSet<MembershipClaim> MembershipClaims => Set<MembershipClaim>();
    public DbSet<ClaimType> ClaimTypes => Set<ClaimType>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Optional: soft-delete query filters (comment out if you don't want global filters).
        modelBuilder.Entity<Organization>().HasQueryFilter(x => x.DeletedAtUtc == null);
        modelBuilder.Entity<User>().HasQueryFilter(x => x.DeletedAtUtc == null);
        modelBuilder.Entity<Membership>().HasQueryFilter(x => x.DeletedAtUtc == null);
        modelBuilder.Entity<Role>().HasQueryFilter(x => x.DeletedAtUtc == null);
        modelBuilder.Entity<Permission>().HasQueryFilter(x => x.DeletedAtUtc == null);

        // External identity uniqueness:
        // Many apps want (ExternalProvider, ExternalId) unique globally. If you want per-tenant, move it to Membership instead.
        modelBuilder.Entity<User>()
            .HasIndex(x => new { x.ExternalProvider, x.ExternalId })
            .IsUnique()
            .HasFilter("[ExternalProvider] IS NOT NULL AND [ExternalId] IS NOT NULL");

        // Relationships
        modelBuilder.Entity<Membership>()
            .HasOne(m => m.Organization)
            .WithMany(o => o.Memberships)
            .HasForeignKey(m => m.OrganizationId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<Membership>()
            .HasOne(m => m.User)
            .WithMany(u => u.Memberships)
            .HasForeignKey(m => m.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<Role>()
            .HasOne(r => r.Organization)
            .WithMany(o => o.Roles)
            .HasForeignKey(r => r.OrganizationId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<OrganizationClaim>()
            .HasOne(c => c.Organization)
            .WithMany(o => o.Claims)
            .HasForeignKey(c => c.OrganizationId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<UserClaim>()
            .HasOne(c => c.User)
            .WithMany(u => u.Claims)
            .HasForeignKey(c => c.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<UserRole>()
            .HasOne(ur => ur.Membership)
            .WithMany(m => m.Roles)
            .HasForeignKey(ur => ur.MembershipId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<UserRole>()
            .HasOne(ur => ur.Role)
            .WithMany(r => r.Members)
            .HasForeignKey(ur => ur.RoleId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<RolePermission>()
            .HasOne(rp => rp.Role)
            .WithMany(r => r.Permissions)
            .HasForeignKey(rp => rp.RoleId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<RolePermission>()
            .HasOne(rp => rp.Permission)
            .WithMany(p => p.Roles)
            .HasForeignKey(rp => rp.PermissionId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<MembershipClaim>()
            .HasOne(c => c.Membership)
            .WithMany(m => m.Claims)
            .HasForeignKey(c => c.MembershipId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
