// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using Dyvenix.App1.Data.Shared.Entities;
using Microsoft.EntityFrameworkCore;

namespace Dyvenix.App1.Data;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    public DbSet<Organization> Organizations => Set<Organization>();
    public DbSet<User> Users => Set<User>();
    public DbSet<Membership> Memberships => Set<Membership>();
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<Permission> Permissions => Set<Permission>();
    public DbSet<RolePermission> RolePermissions => Set<RolePermission>();
    public DbSet<UserRole> UserRoles => Set<UserRole>();
    public DbSet<UserClaim> UserClaims => Set<UserClaim>();
    public DbSet<OrganizationClaim> OrganizationClaims => Set<OrganizationClaim>();
    public DbSet<MembershipClaim> MembershipClaims => Set<MembershipClaim>();
    public DbSet<ClaimType> ClaimTypes => Set<ClaimType>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Optional: soft-delete query filters (comment out if you don't want global filters).
        modelBuilder.Entity<Organization>().HasQueryFilter(x => x.DeletedAtUtc == null);
        modelBuilder.Entity<User>().HasQueryFilter(x => x.DeletedAtUtc == null);
        modelBuilder.Entity<Membership>().HasQueryFilter(x => x.DeletedAtUtc == null);
        modelBuilder.Entity<Role>().HasQueryFilter(x => x.DeletedAtUtc == null);
        modelBuilder.Entity<Permission>().HasQueryFilter(x => x.DeletedAtUtc == null);

        // Organization configuration
        modelBuilder.Entity<Organization>(entity =>
        {
            entity.HasKey(o => o.Id);
            entity.Property(o => o.RowVersion).IsRowVersion();
            
            entity.HasIndex(o => o.Slug).IsUnique();
            entity.Property(o => o.Name).IsRequired().HasMaxLength(200);
            entity.Property(o => o.Slug).IsRequired().HasMaxLength(100);
            entity.Property(o => o.BillingExternalId).HasMaxLength(200);
            entity.Property(o => o.DefaultLocale).HasMaxLength(20);
            entity.Property(o => o.DefaultTimeZone).HasMaxLength(80);
        });

        // User configuration
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(u => u.Id);
            entity.Property(u => u.RowVersion).IsRowVersion();
            
            entity.HasIndex(u => u.NormalizedEmail);
            entity.HasIndex(u => new { u.ExternalProvider, u.ExternalId })
                .IsUnique()
                .HasFilter("[ExternalProvider] IS NOT NULL AND [ExternalId] IS NOT NULL");
            
            entity.Property(u => u.ExternalId).HasMaxLength(200);
            entity.Property(u => u.ExternalProvider).HasMaxLength(50);
            entity.Property(u => u.Email).HasMaxLength(320);
            entity.Property(u => u.NormalizedEmail).HasMaxLength(320);
            entity.Property(u => u.FirstName).HasMaxLength(100);
            entity.Property(u => u.LastName).HasMaxLength(100);
            entity.Property(u => u.DisplayName).HasMaxLength(200);
            entity.Property(u => u.PhoneNumber).HasMaxLength(30);
        });

        // Membership configuration
        modelBuilder.Entity<Membership>(entity =>
        {
            entity.HasKey(m => m.Id);
            entity.Property(m => m.RowVersion).IsRowVersion();
            
            entity.HasIndex(m => new { m.OrganizationId, m.UserId }).IsUnique();
        });

        // Role configuration
        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(r => r.Id);
            entity.Property(r => r.RowVersion).IsRowVersion();
            
            entity.HasIndex(r => new { r.OrganizationId, r.NormalizedName }).IsUnique();
            entity.Property(r => r.Name).IsRequired().HasMaxLength(100);
            entity.Property(r => r.NormalizedName).IsRequired().HasMaxLength(100);
            entity.Property(r => r.Description).HasMaxLength(500);
        });

        // Permission configuration
        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(p => p.Id);
            entity.Property(p => p.RowVersion).IsRowVersion();
            
            entity.HasIndex(p => p.Key).IsUnique();
            entity.Property(p => p.Key).IsRequired().HasMaxLength(200);
            entity.Property(p => p.DisplayName).HasMaxLength(200);
            entity.Property(p => p.Description).HasMaxLength(500);
        });

        // RolePermission configuration
        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasKey(rp => rp.Id);
            entity.Property(rp => rp.RowVersion).IsRowVersion();
            
            entity.HasIndex(rp => new { rp.RoleId, rp.PermissionId }).IsUnique();
        });

        // UserRole configuration
        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(ur => ur.Id);
            entity.Property(ur => ur.RowVersion).IsRowVersion();
            
            entity.HasIndex(ur => new { ur.MembershipId, ur.RoleId }).IsUnique();
        });

        // UserClaim configuration
        modelBuilder.Entity<UserClaim>(entity =>
        {
            entity.HasKey(uc => uc.Id);
            entity.Property(uc => uc.RowVersion).IsRowVersion();
            
            entity.HasIndex(uc => new { uc.UserId, uc.Type, uc.Value }).IsUnique();
            entity.Property(uc => uc.Type).IsRequired().HasMaxLength(200);
            entity.Property(uc => uc.Value).IsRequired().HasMaxLength(500);
            entity.Property(uc => uc.ValueType).HasMaxLength(50);
            entity.Property(uc => uc.Issuer).HasMaxLength(200);
        });

        // OrganizationClaim configuration
        modelBuilder.Entity<OrganizationClaim>(entity =>
        {
            entity.HasKey(oc => oc.Id);
            entity.Property(oc => oc.RowVersion).IsRowVersion();
            
            entity.HasIndex(oc => new { oc.OrganizationId, oc.Type, oc.Value }).IsUnique();
            entity.Property(oc => oc.Type).IsRequired().HasMaxLength(200);
            entity.Property(oc => oc.Value).IsRequired().HasMaxLength(500);
            entity.Property(oc => oc.ValueType).HasMaxLength(50);
            entity.Property(oc => oc.Issuer).HasMaxLength(200);
        });

        // MembershipClaim configuration
        modelBuilder.Entity<MembershipClaim>(entity =>
        {
            entity.HasKey(mc => mc.Id);
            entity.Property(mc => mc.RowVersion).IsRowVersion();
            
            entity.HasIndex(mc => new { mc.MembershipId, mc.Type, mc.Value }).IsUnique();
            entity.Property(mc => mc.Type).IsRequired().HasMaxLength(200);
            entity.Property(mc => mc.Value).IsRequired().HasMaxLength(500);
            entity.Property(mc => mc.ValueType).HasMaxLength(50);
            entity.Property(mc => mc.Issuer).HasMaxLength(200);
        });

        // ClaimType configuration
        modelBuilder.Entity<ClaimType>(entity =>
        {
            entity.HasKey(ct => ct.Id);
            entity.Property(ct => ct.RowVersion).IsRowVersion();
            
            entity.HasIndex(ct => ct.Type).IsUnique();
            entity.Property(ct => ct.Type).IsRequired().HasMaxLength(200);
            entity.Property(ct => ct.DisplayName).HasMaxLength(200);
            entity.Property(ct => ct.Description).HasMaxLength(500);
        });

        // Relationships
        modelBuilder.Entity<Membership>()
            .HasOne(m => m.Organization)
            .WithMany(o => o.Memberships)
            .HasForeignKey(m => m.OrganizationId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<Membership>()
            .HasOne(m => m.User)
            .WithMany(u => u.Memberships)
            .HasForeignKey(m => m.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<Role>()
            .HasOne(r => r.Organization)
            .WithMany(o => o.Roles)
            .HasForeignKey(r => r.OrganizationId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<OrganizationClaim>()
            .HasOne(c => c.Organization)
            .WithMany(o => o.Claims)
            .HasForeignKey(c => c.OrganizationId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<UserClaim>()
            .HasOne(c => c.User)
            .WithMany(u => u.Claims)
            .HasForeignKey(c => c.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<UserRole>()
            .HasOne(ur => ur.Membership)
            .WithMany(m => m.Roles)
            .HasForeignKey(ur => ur.MembershipId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<UserRole>()
            .HasOne(ur => ur.Role)
            .WithMany(r => r.Members)
            .HasForeignKey(ur => ur.RoleId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<RolePermission>()
            .HasOne(rp => rp.Role)
            .WithMany(r => r.Permissions)
            .HasForeignKey(rp => rp.RoleId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<RolePermission>()
            .HasOne(rp => rp.Permission)
            .WithMany(p => p.Roles)
            .HasForeignKey(rp => rp.PermissionId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<MembershipClaim>()
            .HasOne(c => c.Membership)
            .WithMany(m => m.Claims)
            .HasForeignKey(c => c.MembershipId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
