// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;
using System.ComponentModel.DataAnnotations;

namespace Dyvenix.App1.Data.Shared.Entities;

/// <summary>
/// Optional catalog of claim types you use in your app.
/// If you don't want a registry, you can remove this and store strings directly.
/// </summary>
public class ClaimType : EntityBase
{
    public string Type { get; set; } = string.Empty; // e.g., "plan", "feature", "department", "region"

    public string? DisplayName { get; set; }

    public string? Description { get; set; }
}

