// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;
using System.ComponentModel.DataAnnotations;

namespace App1.App1.Data.Entities;

public abstract class EntityBase
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>UTC time the row was created.</summary>
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;

    /// <summary>UTC time the row was last updated.</summary>
    public DateTime? UpdatedAtUtc { get; set; }

    /// <summary>Soft-delete marker.</summary>
    public DateTime? DeletedAtUtc { get; set; }

    /// <summary>Optional audit user id.</summary>
    public Guid? CreatedByUserId { get; set; }

    /// <summary>Optional audit user id.</summary>
    public Guid? UpdatedByUserId { get; set; }

    /// <summary>Optional audit user id.</summary>
    public Guid? DeletedByUserId { get; set; }

    /// <summary>Optimistic concurrency token.</summary>
    [Timestamp]
    public byte[] RowVersion { get; set; } = Array.Empty<byte>();

    public bool IsDeleted => DeletedAtUtc.HasValue;
}
