// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Dyvenix.App1.Data.Entities;

/// <summary>
/// Join table: a user can belong to multiple organizations (common in SaaS),
/// and have different roles/claims per org.
/// </summary>
[Index(nameof(OrganizationId), nameof(UserId), IsUnique = true)]
public class Membership : EntityBase
{
    public Guid OrganizationId { get; set; }
    public Organization Organization { get; set; } = null!;

    public Guid UserId { get; set; }
    public User User { get; set; } = null!;

    public MembershipStatus Status { get; set; } = MembershipStatus.Active;

    /// <summary>Whether the user is an org admin (convenience flag).</summary>
    public bool IsOrganizationAdmin { get; set; }

    public ICollection<UserRole> Roles { get; set; } = new List<UserRole>();
    public ICollection<MembershipClaim> Claims { get; set; } = new List<MembershipClaim>();
}

public enum MembershipStatus : short
{
    Invited = 0,
    Active = 1,
    Suspended = 2,
    Removed = 9
}
