// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace Dyvenix.App1.Data.Entities;

/// <summary>
/// Claim attached to a Membership (user-in-tenant).
/// Use this for per-tenant user claims like "department", "site", "customerRole", etc.
/// </summary>
[Index(nameof(MembershipId), nameof(Type), nameof(Value), IsUnique = true)]
public class MembershipClaim : EntityBase
{
    public Guid MembershipId { get; set; }
    public Membership Membership { get; set; } = null!;

    [Required, MaxLength(200)]
    public string Type { get; set; } = string.Empty;

    [Required, MaxLength(500)]
    public string Value { get; set; } = string.Empty;

    [MaxLength(50)]
    public string? ValueType { get; set; }

    [MaxLength(200)]
    public string? Issuer { get; set; }
}
