// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;

namespace Dyvenix.App1.Data.Shared.Entities;

/// <summary>
/// Claim attached to a Membership (user-in-tenant).
/// Use this for per-tenant user claims like "department", "site", "customerRole", etc.
/// </summary>
public class MembershipClaim : EntityBase
{
    public Guid MembershipId { get; set; }
    public Membership Membership { get; set; } = null!;

    public string Type { get; set; } = string.Empty;

    public string Value { get; set; } = string.Empty;

    public string? ValueType { get; set; }

    public string? Issuer { get; set; }
}
