// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;
using System.Collections.Generic;

namespace Dyvenix.App1.Data.Shared.Entities;

/// <summary>
/// Represents a tenant / organization in a multi-tenant SaaS.
/// </summary>
public class Organization : EntityBase
{
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// URL-friendly unique key for the tenant (e.g., used in subdomain or path).
    /// </summary>
    public string Slug { get; set; } = string.Empty;

    /// <summary>
    /// Optional external billing/customer identifier (Stripe customer id, etc.).
    /// </summary>
    public string? BillingExternalId { get; set; }

    /// <summary>
    /// Tenant status flag (active/suspended etc.).
    /// </summary>
    public OrganizationStatus Status { get; set; } = OrganizationStatus.Active;

    /// <summary>
    /// Default locale/culture for the tenant.
    /// </summary>
    public string? DefaultLocale { get; set; }

    /// <summary>
    /// Default time zone id (IANA or Windows id - pick one standard).
    /// </summary>
    public string? DefaultTimeZone { get; set; }

    /// <summary>
    /// Optional metadata as JSON (feature flags, settings, etc.).
    /// </summary>
    public string? MetadataJson { get; set; }

    public ICollection<OrganizationClaim> Claims { get; set; } = new List<OrganizationClaim>();
    public ICollection<Membership> Memberships { get; set; } = new List<Membership>();
    public ICollection<Role> Roles { get; set; } = new List<Role>();
}
