// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace Dyvenix.App1.Data.Entities;

/// <summary>
/// Claim attached to an Organization (tenant-level settings/features).
/// </summary>
[Index(nameof(OrganizationId), nameof(Type), nameof(Value), IsUnique = true)]
public class OrganizationClaim : EntityBase
{
    public Guid OrganizationId { get; set; }
    public Organization Organization { get; set; } = null!;

    [Required, MaxLength(200)]
    public string Type { get; set; } = string.Empty;

    [Required, MaxLength(500)]
    public string Value { get; set; } = string.Empty;

    [MaxLength(50)]
    public string? ValueType { get; set; }

    [MaxLength(200)]
    public string? Issuer { get; set; }
}
