// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;

namespace Dyvenix.App1.Data.Shared.Entities;

/// <summary>
/// Claim attached to an Organization (tenant-level settings/features).
/// </summary>
public class OrganizationClaim : EntityBase
{
    public Guid OrganizationId { get; set; }
    public Organization Organization { get; set; } = null!;

    public string Type { get; set; } = string.Empty;

    public string Value { get; set; } = string.Empty;

    public string? ValueType { get; set; }

    public string? Issuer { get; set; }
}
