// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace App1.App1.Data.Entities;

/// <summary>
/// Represents an app permission. Usually global (not per tenant), but you can scope it if you want.
/// Examples:
/// - "orders.read"
/// - "orders.write"
/// - "admin.users.manage"
/// </summary>
[Index(nameof(Key), IsUnique = true)]
public class Permission : EntityBase
{
    [Required, MaxLength(200)]
    public string Key { get; set; } = string.Empty;

    [MaxLength(200)]
    public string? DisplayName { get; set; }

    [MaxLength(500)]
    public string? Description { get; set; }

    public ICollection<RolePermission> Roles { get; set; } = new List<RolePermission>();
}
