// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;
using System.Collections.Generic;

namespace Dyvenix.App1.Data.Shared.Entities;

/// <summary>
/// Represents an app permission. Usually global (not per tenant), but you can scope it if you want.
/// Examples:
/// - "orders.read"
/// - "orders.write"
/// - "admin.users.manage"
/// </summary>
public class Permission : EntityBase
{
    public string Key { get; set; } = string.Empty;

    public string? DisplayName { get; set; }

    public string? Description { get; set; }

    public ICollection<RolePermission> Roles { get; set; } = new List<RolePermission>();
}
