// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;
using Microsoft.EntityFrameworkCore;

namespace App1.App1.Data.Entities;

/// <summary>
/// Many-to-many join for Role <-> Permission.
/// </summary>
[Index(nameof(RoleId), nameof(PermissionId), IsUnique = true)]
public class RolePermission : EntityBase
{
    public Guid RoleId { get; set; }
    public Role Role { get; set; } = null!;

    public Guid PermissionId { get; set; }
    public Permission Permission { get; set; } = null!;
}
