// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace App1.App1.Data.Entities;

/// <summary>
/// Role scoped to an Organization.
/// </summary>
[Index(nameof(OrganizationId), nameof(NormalizedName), IsUnique = true)]
public class Role : EntityBase
{
    public Guid OrganizationId { get; set; }
    public Organization Organization { get; set; } = null!;

    [Required, MaxLength(100)]
    public string Name { get; set; } = string.Empty;

    [Required, MaxLength(100)]
    public string NormalizedName { get; set; } = string.Empty;

    [MaxLength(500)]
    public string? Description { get; set; }

    public bool IsSystemRole { get; set; } // e.g., "Owner", "Admin" shipped by you

    public ICollection<RolePermission> Permissions { get; set; } = new List<RolePermission>();
    public ICollection<UserRole> Members { get; set; } = new List<UserRole>();
}
