// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;

namespace Dyvenix.App1.Data.Shared.Entities;

/// <summary>
/// Claim attached globally to a User (not tenant-specific).
/// For tenant-specific claims, prefer MembershipClaim.
/// </summary>
public class UserClaim : EntityBase
{
    public Guid UserId { get; set; }
    public User User { get; set; } = null!;

    public string Type { get; set; } = string.Empty;

    public string Value { get; set; } = string.Empty;

    public string? ValueType { get; set; } // optional: "string", "bool", "int", etc.

    public string? Issuer { get; set; } // optional
}
