// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable

namespace Dyvenix.App1.Data.Shared.Entities;

public enum UserStatus : short
{
    Active = 1,
    Disabled = 2,
    Locked = 3,
    Deleted = 9
}
