// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace App1.App1.Data.Entities;

/// <summary>
/// A person/account in your system. Authentication happens at an external IdP.
/// Authorization is enforced via roles/claims in your DB.
/// </summary>
[Index(nameof(NormalizedEmail))]
public class User : EntityBase
{
    /// <summary>
    /// IdP subject/oid/etc. (e.g. Entra "oid" or "sub"). Not unique globally unless combined with Provider.
    /// </summary>
    [MaxLength(200)]
    public string? ExternalId { get; set; }

    /// <summary>
    /// Identifier for the IdP (e.g. "EntraID", "EntraExternal", "Auth0", "Okta").
    /// </summary>
    [MaxLength(50)]
    public string? ExternalProvider { get; set; }

    [MaxLength(320)]
    public string? Email { get; set; }

    /// <summary>Store a normalized email for case-insensitive lookups.</summary>
    [MaxLength(320)]
    public string? NormalizedEmail { get; set; }

    [MaxLength(100)]
    public string? FirstName { get; set; }

    [MaxLength(100)]
    public string? LastName { get; set; }

    [MaxLength(200)]
    public string? DisplayName { get; set; }

    [MaxLength(30)]
    public string? PhoneNumber { get; set; }

    public bool EmailVerified { get; set; }
    public bool PhoneVerified { get; set; }

    public UserStatus Status { get; set; } = UserStatus.Active;

    /// <summary>
    /// Optional JSON metadata (preferences, UI settings, etc.).
    /// </summary>
    public string? MetadataJson { get; set; }

    public ICollection<UserClaim> Claims { get; set; } = new List<UserClaim>();
    public ICollection<Membership> Memberships { get; set; } = new List<Membership>();
}

public enum UserStatus : short
{
    Active = 1,
    Disabled = 2,
    Locked = 3,
    Deleted = 9
}
