// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace App1.App1.Data.Entities;

/// <summary>
/// Claim attached globally to a User (not tenant-specific).
/// For tenant-specific claims, prefer MembershipClaim.
/// </summary>
[Index(nameof(UserId), nameof(Type), nameof(Value), IsUnique = true)]
public class UserClaim : EntityBase
{
    public Guid UserId { get; set; }
    public User User { get; set; } = null!;

    [Required, MaxLength(200)]
    public string Type { get; set; } = string.Empty;

    [Required, MaxLength(500)]
    public string Value { get; set; } = string.Empty;

    [MaxLength(50)]
    public string? ValueType { get; set; } // optional: "string", "bool", "int", etc.

    [MaxLength(200)]
    public string? Issuer { get; set; } // optional
}
