// <auto-generated/>
// Basic multi-tenant SaaS entities (EF Core code-first)
// Notes:
// - Guid keys by default
// - Soft-delete + audit fields included
// - Concurrency token RowVersion included
// - "ExternalId" is the IdP subject/oid/etc. + Provider identifies the IdP

#nullable enable
using System;

namespace Dyvenix.App1.Data.Shared.Entities;

/// <summary>
/// Assigns a role to a user within a specific organization membership.
/// </summary>
public class UserRole : EntityBase
{
    public Guid MembershipId { get; set; }
    public Membership Membership { get; set; } = null!;

    public Guid RoleId { get; set; }
    public Role Role { get; set; } = null!;
}
